#!/bin/bash
# This script add files and driectories to the staging area,
# commit them to the repo and push to the remote repo.

# $1 - the first argument: the path to the working directory of the repo.
# $2 - the second argument: message to commit.
PWD=$(pwd)

if [ $1 ]
then
	cd $1
else
	echo "Error: Argument required: local repo's direcrory"
	exit 1
fi

git add .
git commit
git pull && git push

cd $PWD

# Note that this script will only work if there is an existing local repo.
