#!/bin/bash

# $1 - GitHub username
# $2 - The repository's name

if [[ ! ($1 && $2) ]]
then
	echo "Error: Arguments required - 2"
	exit 1
fi

if git clone -q "https://github.com/$1/$2"
then
	echo "$2 cloned successfully!"
	exit 0
fi
